id: P6F64677F
initial_creation_type: input
source_metadata:
  title: 'BA: Gaṇḍavyūhasūtra'
  language: zh
  volumes:
    b93a2413619c4f75b3f6b5685ac34618:
      title: Nidāna
      base_file: Nidāna.txt
      work_id: W46957208
    6a4907e0722042e0860857f755f16507:
      title: Samantabhadra
      base_file: Samantabhadra.txt
      work_id: W0808B24D
    b19e55004bac4f3a90b6a3e7ad3725c0:
      title: Title
      base_file: Title.txt
      work_id: W9893BCB6
  chapter_to_tile: {}
created_at: '2022-03-01T21:28:05.277483'
last_modified_at: '2022-03-01T21:28:05.277490'
